#!/bin/bash

date=$(date +"%Y-%m-%d")
filepath="/tmp"

output_file="${filepath}/subscriptions_aggregate_${date}.csv"

psql -d tchap_stats -c "REFRESH MATERIALIZED VIEW internal.users_by_instance;"
psql -d tchap_stats -c "COPY (SELECT * FROM external.subscriptions_aggregate) TO '$output_file' WITH (FORMAT CSV, HEADER)"

upload_s3 $output_file